### ISSUE TITLE
结构体字段注释快捷键不起作用

### ISSUE THREAD

**Issue by Lawson08** [0x00b/vscode-go-comment#1]
想问一下，为什么我的结构体字段注释快捷键不起作用，函数、类型注释快捷键是起作用的

**Comment by Lawson08** [comment]
就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的

**Comment by 0x00b** [comment]
> 就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的

我这两天写一下，之前是goland的版本实现了

**Comment by Lawson08** [comment]
> > 就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的
> 
> 我这两天写一下，之前是goland的版本实现了

期待😋

**Comment by 0x00b** [comment]
> > > 就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的
> > 
> > 
> > 我这两天写一下，之前是goland的版本实现了
> 
> 期待😋

已经升级啦，0.0.4版本支持变量啦

**Comment by Lawson08** [comment]
> > > > 就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的
> > > 
> > > 
> > > 我这两天写一下，之前是goland的版本实现了
> > 
> > 
> > 期待😋
> 
> 已经升级啦，0.0.4版本支持变量啦

tql，大佬！！这下再也不怕golint😋

**Comment by 0x00b** [comment]
> > > > > 就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的
> > > > 
> > > > 
> > > > 我这两天写一下，之前是goland的版本实现了
> > > 
> > > 
> > > 期待😋
> > 
> > 
> > 已经升级啦，0.0.4版本支持变量啦
> 
> tql，大佬！！这下再也不怕golint😋

发现了一个bug，升级一下0.0.5哈😋

**Comment by Lawson08** [comment]
> > > > > > 就是GIF演示中的KeyFile、Middlewares这些字段在我的vscode上`ctl+command+/`是不起作用的
> > > > > 
> > > > > 
> > > > > 我这两天写一下，之前是goland的版本实现了
> > > > 
> > > > 
> > > > 期待😋
> > > 
> > > 
> > > 已经升级啦，0.0.4版本支持变量啦
> > 
> > 
> > tql，大佬！！这下再也不怕golint😋
> 
> 发现了一个bug，升级一下0.0.5哈😋

收到
