### ISSUE TITLE
date变量的时间能否设置成24小时制

### ISSUE THREAD

**Issue by Robert-Du0001** [0x00b/vscode-go-comment#10]
模板是这样设置的

```json
{
  "functionTemplate": "// ${func_name} \n//  @receiver ${receiver_name} \n//  @param ${param_name} \n//  @return ${return_name} \n//  @author ${git_name} \n//  @date ${date}"
}
```

然后出注释如下：

```
// Translate 
//  @param err 
//  @return string 
//  @author Robert 
//  @date 2024-10-25 08:02:53 
```

我想要能设置成24小时制的:

```
// Translate 
//  @param err 
//  @return string 
//  @author Robert 
//  @date 2024-10-25 20:02:53 
```

**Comment by 0x00b** [comment]
非常合理，这就去改

**Comment by 0x00b** [comment]
> 模板是这样设置的
> 
> ```json
> {
>   "functionTemplate": "// ${func_name} \n//  @receiver ${receiver_name} \n//  @param ${param_name} \n//  @return ${return_name} \n//  @author ${git_name} \n//  @date ${date}"
> }
> ```
> 
> 然后出注释如下：
> 
> ```
> // Translate 
> //  @param err 
> //  @return string 
> //  @author Robert 
> //  @date 2024-10-25 08:02:53 
> ```
> 
> 我想要能设置成24小时制的:
> 
> ```
> // Translate 
> //  @param err 
> //  @return string 
> //  @author Robert 
> //  @date 2024-10-25 20:02:53 
> ```


非常合理，这就去改

**Comment by Robert-Du0001** [comment]
感谢感谢

**Comment by 0x00b** [comment]
0.1.3版本支持了，更新下应该可以了

**Comment by Robert-Du0001** [comment]
好的好的 感谢😃
