### ISSUE TITLE
请问，怎么增加Auther跟date这两个？

### ISSUE THREAD

**Issue by endingman** [0x00b/vscode-go-comment#2]
如题。

**Comment by 0x00b** [comment]
> 如题。

嗯。。。这两个我没怎么用，所以支持还有点问题，需要的话我这两天加一下:smile:

**Comment by endingman** [comment]
嗯嗯，我是比较习惯，因为工作协作有什么问题的话可以跟负责的人协作问题什么的，这样不用看git log谁负责的东西。

**Comment by 0x00b** [comment]
> 如题。

刚刚0.0.7版本支持了这两个关键字，可能需要你在设置中设置一下模版内容（需要使用json配置的方式打开vscode配置，如果有疑问可以再沟通），参考如下：

    "functionTemplate": "// ${func_name} \n//  @receiver ${receiver_name} \n//  @param ${param_name} \n//  @return ${return_name} \n//  @author ${git_name} \n//  @date ${date} ",

	// 
	// "typeTemplate": "// ${type_name} \n//  @author ${git_name} \n//  @date ${date} ",

	// 
	// "varTemplate": "// ${var_name} \n//  @author ${git_name} \n//  @date ${date} ",
