### ISSUE TITLE
安装extension后无法找到命令`vscodeGoComment.AutoComment`

### ISSUE THREAD

**Issue by kevinmatthe** [0x00b/vscode-go-comment#4]
![image](https://user-images.githubusercontent.com/36391318/148420638-823e86c2-7076-4b70-b044-2362fe4ddf3e.png)

**Comment by 0x00b** [comment]
你好呀，使用方法是光标指向想要生成注释的函数或变量等，然后使用快捷键 。mac使用：control + command + /  ，windows使用: control + alt + /)， 不知道你想用命令的方式是想实现啥样的效果呢？

**Comment by 0x00b** [comment]
没有其他问题的话，就先关闭了哈
