### ISSUE TITLE
Golang函数生成注释有误

### ISSUE THREAD

**Issue by elchn** [0x00b/vscode-go-comment#5]
1. 模板
"functionTemplate": "// ${func_name} \n//  receiver ${receiver_name} ${receiver_type}\n//  param ${param_name} ${param_type}\n//  return ${return_name} ${return_type}",
2. 结果 
![image](https://user-images.githubusercontent.com/33387551/154058472-d97f0e03-43eb-49f2-afef-9ce01034c20e.png)
3. xxx_name和xxx_type变量未正确替换
4. 请看一下吧

**Comment by 0x00b** [comment]
> 1. 模板
>    "functionTemplate": "// ${func_name} \n//  receiver ${receiver_name} ${receiver_type}\n//  param ${param_name} ${param_type}\n//  return ${return_name} ${return_type}",
> 2. 结果
>    ![image](https://user-images.githubusercontent.com/33387551/154058472-d97f0e03-43eb-49f2-afef-9ce01034c20e.png)
> 3. xxx_name和xxx_type变量未正确替换
> 4. 请看一下吧

感谢使用，我会尽快看看的☺️

**Comment by 0x00b** [comment]
> 1. 模板
>    "functionTemplate": "// ${func_name} \n//  receiver ${receiver_name} ${receiver_type}\n//  param ${param_name} ${param_type}\n//  return ${return_name} ${return_type}",
> 2. 结果
>    ![image](https://user-images.githubusercontent.com/33387551/154058472-d97f0e03-43eb-49f2-afef-9ce01034c20e.png)
> 3. xxx_name和xxx_type变量未正确替换
> 4. 请看一下吧

可以尝试用下面这个，因为receiver，param，return是关键字，要用@开头，比如 @param，为什么一定要用@开头呢？是因为参数可能存在多个，每个参数的注释占用一行，所以以@param开头，就知道这行模版是用来生成参数对应的注释，这样两个参数就会有两行，都以@param开头，不知道我这样解释，能不能解决你的疑惑
"functionTemplate": "// ${func_name} \n// @receiver ${receiver_name} ${receiver_type}\n// @param ${param_name} ${param_type}\n// @return ${return_name} ${return_type}",

当然，不以@开头也是可以的， 比如规定 // param就是参数注释模版行，但有时候会用/**/注释，这个时候就不好判断了， 有些人喜欢这样写，总之就是情况很多，如果用@开头就很明确了
```
/**
 ** param ...
 */
```
