### ISSUE TITLE
作者还维护吗,泛型函数好像有些问题

### ISSUE THREAD

**Issue by tiansin** [0x00b/vscode-go-comment#7]
RT

**Comment by 0x00b** [comment]
具体情况是啥呢？我现在不怎么写go了，所以没有太多精力关注这个。。

**Comment by tiansin** [comment]
@0x00b 如果是泛型函数,按生成注释的快捷键只会生成 `// func ` 这行代码出来

**Comment by Kevinello** [comment]
同问，类型注解没有支持上
如：
`func TimeCostWithTps[DValue string | *string](start time.Time, moduleName string, DList ...DValue) `

**Comment by 0x00b** [comment]
先更新一个版本，已经支持识别泛型啦，
<img width="735" alt="image" src="https://user-images.githubusercontent.com/18435234/198305264-e08b6fa6-0910-4bd3-b0ee-4e00488dd54d.png">
不过还不支持对泛型的单项说明，类似下面这样，需要的话可以搞上
<img width="703" alt="image" src="https://user-images.githubusercontent.com/18435234/198305724-54aefb70-abee-40f9-945e-5ed734f1db0f.png">
