### ISSUE TITLE
我修改了模板规则但是不生效 

### ISSUE THREAD

**Issue by hub607** [0x00b/vscode-go-comment#8]
```
  "functionTemplate": "// ${func_name} \n// @receiver ${receiver_name} \n// @param ${param_name} \n// @return ${return_name} \n// @Author 测试人员1 \n//",
  "typeTemplate": "// ${type_name} "
```

但是生成时并没有带上 @Author 这个属性
![image](https://user-images.githubusercontent.com/38717760/206667829-6cae9942-31f4-4178-a9ad-ec6192c5cdeb.png)

**Comment by 0x00b** [comment]
Author -> author, 都是用的小写的关键字哦，你改一下看看生效不? 你用的是git吗？如果是的话，可以试一下下面这个。

    "functionTemplate": "// ${func_name} \n// @receiver ${receiver_name} \n// @param ${param_name} \n// @return ${return_name} \n// @author 测试人员1 ${git_name} \n//",

**Comment by hub607** [comment]
> 作者 -> 作者， 都是用的小写的关键字哦，你改一下看看生效不？你用的是git吗？如果是的话，可以试一下下面这个。
> 
> ```
> "functionTemplate": "// ${func_name} \n// @receiver ${receiver_name} \n// @param ${param_name} \n// @return ${return_name} \n// @author 测试人员1 ${git_name} \n//",
> ```

okok 我试一下

**Comment by hub607** [comment]
> Author -> author, 都是用的小写的关键字哦，你改一下看看生效不? 你用的是git吗？如果是的话，可以试一下下面这个。
> 
> ```
> "functionTemplate": "// ${func_name} \n// @receiver ${receiver_name} \n// @param ${param_name} \n// @return ${return_name} \n// @author 测试人员1 ${git_name} \n//",
> ```

改成小写是可以的   谢谢
